.TH TRUELIES "1" "October 2018" "Truelies 1.2" "User Commands"
.SH NAME
Truelies \- A truth-table for the command-line.
.SH DESCRIPTION
Truelies is a truth-table for the command-line written in BASH.
.SH OPTIONS
.TP
\fB\-\-and\fR Displays the truth table with an AND operation.
.PP
\fB\-\-or\fR Displays the truth table with an OR operation.
.PP
\fB\-\-xor\fR Displays the truth table with an XOR operation.
.PP
\fB\-\-not\fR Displays the truth table with a NOT operation.
.PP
\fB\-\-help\fR Shows the help menue.
.PP
\fB\-\-version\fR Shows version.
.SH AUTHOR
Alexander Bodin
.PP
https://github.com/AlexanderBodin
.SH COPYRIGHT
MIT License

Copyright (c) 2018 Alexander Bodin

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

